version: '2'

services:
  redis:
    image: redis:5
  postgres:
    image: postgres:11.6
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aero_chat
    networks:
      - djangonetwork
  web:
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_CONFIGURATION=Production
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - djangonetwork

networks:
  djangonetwork:
      driver: bridge
