site_name: apps
site_description: wonderfull messenger
repo_url: https://github.com/saylau/messenger
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/saylau">saylau</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
